/* SPDX-License-Identifier: MPL-2.0 */
/*
 * maelys-oci: the terminal of libmaelys-oci, built on libmaelys_cli. It is
 * a consumer of <maelys/oci.h> like any other program: the catalog below is
 * the only source of usage text, every handler consumes the validated
 * invocation, runs one public operation and replies once through the
 * framework. Nothing here reaches into the library's sources.
 */
#include <maelys/cli.h>
#include <maelys/oci.h>

#include "schemas.h" /* generated by maelys-cli-embed from cli/schemas/ */

#include <limits.h>
#include <stdint.h>
#include <stdlib.h>

/* Preparation helpers may reply through the framework; callers test
 * maelys_cli_replied() after each of them, as the framework guide asks. */

static const char *const digest_algorithms[] = {"sha256", NULL};

/* ---- framework glue ------------------------------------------------------------ */

static const char *error_code(maelys_oci_result_t result) {
    switch (result) {
        case MAELYS_OCI_ERR_ARGUMENT: return MAELYS_CLI_CODE_VALIDATION_FAILED;
        case MAELYS_OCI_ERR_NOT_FOUND: return MAELYS_CLI_CODE_NOT_FOUND;
        case MAELYS_OCI_ERR_ACCESS: return MAELYS_CLI_CODE_ACCESS_DENIED;
        case MAELYS_OCI_ERR_PROTOCOL: return MAELYS_CLI_CODE_PROTOCOL_FAILED;
        case MAELYS_OCI_ERR_STATE: return MAELYS_CLI_CODE_PRECONDITION_FAILED;
        case MAELYS_OCI_ERR_IO: return MAELYS_CLI_CODE_IO_FAILED;
        case MAELYS_OCI_ERR_UNSUPPORTED: return MAELYS_CLI_CODE_UNSUPPORTED;
        case MAELYS_OCI_ERR_MEMORY:
        case MAELYS_OCI_OK:
        default: return MAELYS_CLI_CODE_UNEXPECTED;
    }
}

static const char *error_hint(maelys_oci_result_t result) {
    switch (result) {
        case MAELYS_OCI_ERR_ARGUMENT:
            return "Correct the stated value and retry.";
        case MAELYS_OCI_ERR_NOT_FOUND:
            return "Check the path or reference and retry.";
        case MAELYS_OCI_ERR_ACCESS:
            return "Fix the ownership and modes of the named file, then retry.";
        case MAELYS_OCI_ERR_PROTOCOL:
            return "Obtain a canonical OCI image; the content or the registry "
                   "answer is invalid.";
        case MAELYS_OCI_ERR_STATE:
            return "Inspect the store with 'verify' or select the target "
                   "explicitly, then retry.";
        case MAELYS_OCI_ERR_IO:
            return "Retry; if the failure persists run 'verify' then 'gc'.";
        case MAELYS_OCI_ERR_UNSUPPORTED:
            return "Use a supported host, platform or build.";
        case MAELYS_OCI_ERR_MEMORY:
        case MAELYS_OCI_OK:
        default:
            return "Report this defect to the command implementation.";
    }
}

/* Replies with the library diagnostic and releases it. */
static int fail_with(
    maelys_cli_context_t *context, maelys_oci_result_t result, char *error) {
    int status = maelys_cli_fail(context, error_code(result), error_hint(result),
        "%s", error ? error : "The operation failed.");
    maelys_oci_error_free(error);
    return status;
}

/* Replies with a document through the trusted writer and releases it.
 * Without --format the framework prints the same document indented: the
 * schema is the only representation, there is no prose rendering to parse. */
static int succeed_document(
    maelys_cli_context_t *context, maelys_oci_document_t *document,
    int exit_code) {
    char *text = maelys_oci_document_text(document);
    maelys_oci_document_release(&document);
    if (!text)
        return maelys_cli_fail(context, MAELYS_CLI_CODE_UNEXPECTED,
            "Report this defect to the command implementation.",
            "Cannot serialize the command data.");
    int result = maelys_cli_succeed_trusted(context, text, NULL, exit_code);
    maelys_oci_text_free(text);
    return result;
}

/* --store (validated absolute by the parser), else the library's default;
 * the library names the environment when neither exists. */
static const char *store_option(maelys_cli_context_t *context) {
    return maelys_cli_option(context, "store");
}

/* OS/ARCH has no framework kind: the library validates the shape. */
static int validate_platform_option(maelys_cli_context_t *context) {
    const char *platform = maelys_cli_option(context, "platform");
    if (platform && !maelys_oci_platform_valid(platform))
        return maelys_cli_fail(context, MAELYS_CLI_CODE_VALIDATION_FAILED,
            "Pass --platform OS/ARCH with lowercase components, for example "
            "linux/arm64.", "--platform %s is not OS/ARCH.", platform);
    return 0;
}

/* ---- inspect ------------------------------------------------------------------------ */

static const maelys_cli_operand_t source_operands[] = {
    {MAELYS_CLI_OPERAND("SOURCE",
     "OCI layout directory or tar archive with oci-layout and index.json.")},
};

static int command_inspect(maelys_cli_context_t *context) {
    maelys_oci_document_t *document = NULL;
    char *error = NULL;
    maelys_oci_result_t result =
        maelys_oci_inspect(maelys_cli_operand(context, 0u), &document, &error);
    if (result != MAELYS_OCI_OK) return fail_with(context, result, error);
    return succeed_document(context, document, MAELYS_CLI_EXIT_OK);
}

/* ---- import ---------------------------------------------------------------------------- */

#define STORE_SUMMARY \
    "Private store root; defaults to $" MAELYS_OCI_ENV_STORE " or " \
    "$XDG_DATA_HOME/maelys-oci."
static const maelys_cli_option_t import_options[] = {
    {MAELYS_CLI_ABSOLUTE_PATH("store", "DIRECTORY",
     STORE_SUMMARY " Created on --apply when absent.")},
    {MAELYS_CLI_STRING("platform", "OS/ARCH",
     "Select the manifest of this platform when the source has several.")},
    {MAELYS_CLI_DIGEST("digest", "sha256:HEX",
     "Select the manifest with this digest when the source has several.",
     digest_algorithms)},
    MAELYS_CLI_APPLY_OPTION,
};

static int command_import(maelys_cli_context_t *context) {
    int status = validate_platform_option(context);
    if (maelys_cli_replied(context)) return status;
    maelys_oci_import_options_t *options = NULL;
    if (maelys_oci_import_options_create(&options) != MAELYS_OCI_OK ||
        maelys_oci_import_options_set_store(options, store_option(context)) != MAELYS_OCI_OK ||
        maelys_oci_import_options_set_platform(options, maelys_cli_option(context, "platform")) != MAELYS_OCI_OK ||
        maelys_oci_import_options_set_digest(options, maelys_cli_option(context, "digest")) != MAELYS_OCI_OK ||
        maelys_oci_import_options_set_apply(options, maelys_cli_flag(context, "apply")) != MAELYS_OCI_OK) {
        maelys_oci_import_options_release(&options);
        return maelys_cli_fail(context, MAELYS_CLI_CODE_UNEXPECTED,
            "Report this defect to the command implementation.",
            "Cannot construct validated import options.");
    }
    maelys_oci_document_t *document = NULL;
    char *error = NULL;
    maelys_oci_result_t result = maelys_oci_import(options,
        maelys_cli_operand(context, 0u), &document, &error);
    maelys_oci_import_options_release(&options);
    if (result != MAELYS_OCI_OK) return fail_with(context, result, error);
    return succeed_document(context, document, MAELYS_CLI_EXIT_OK);
}

/* ---- pull ---------------------------------------------------------------------------- */

static const maelys_cli_operand_t pull_operands[] = {
    {MAELYS_CLI_OPERAND("REFERENCE",
     "Immutable image reference REGISTRY/REPOSITORY@sha256:HEX.")},
};

static const char *const pull_platforms[] = {"linux/arm64", "linux/amd64", NULL};

static const maelys_cli_option_t pull_options[] = {
    {MAELYS_CLI_CHOICE("platform",
     "Platform to select from a multi-platform index.", pull_platforms)},
    {MAELYS_CLI_ABSOLUTE_PATH("store", "DIRECTORY",
     STORE_SUMMARY " Created when absent.")},
    {MAELYS_CLI_ABSOLUTE_PATH("ca-file", "FILE",
     "CA bundle; defaults to SSL_CERT_FILE or the system bundle.")},
    {MAELYS_CLI_ABSOLUTE_PATH("token-file", "FILE",
     "Private file holding a registry bearer token."),
     .conflicts_with = "docker-config"},
    {MAELYS_CLI_ABSOLUTE_PATH("docker-config", "FILE",
     "Private Docker config.json with static auths; credential helpers are "
     "refused."), .conflicts_with = "token-file"},
    {MAELYS_CLI_UNSIGNED("timeout-ms", "N",
     "Global acquisition deadline in milliseconds.", 1u, MAELYS_OCI_PULL_TIMEOUT_MAX_MS),
     MAELYS_CLI_DEFAULT_OF(MAELYS_OCI_PULL_TIMEOUT_MS)},
};

static int command_pull(maelys_cli_context_t *context) {
    char default_store[PATH_MAX];
    const char *store = store_option(context);
    if (!store) {
        if (maelys_oci_store_default_path(default_store, sizeof(default_store)) != 0)
            return maelys_cli_fail(context, MAELYS_CLI_CODE_PRECONDITION_FAILED,
                "Pass --store DIRECTORY or set HOME, XDG_DATA_HOME or "
                MAELYS_OCI_ENV_STORE ".",
                "No private OCI store location is configured.");
        store = default_store;
    }
    maelys_oci_pull_options_t *options = NULL;
    uint64_t timeout_ms = 0u;
    (void)maelys_cli_option_unsigned(context, "timeout-ms", &timeout_ms);
    if (maelys_oci_pull_options_create(&options) != MAELYS_OCI_OK ||
        maelys_oci_pull_options_set_ca_file(options, maelys_cli_option(context, "ca-file")) != MAELYS_OCI_OK ||
        maelys_oci_pull_options_set_token_file(options, maelys_cli_option(context, "token-file")) != MAELYS_OCI_OK ||
        maelys_oci_pull_options_set_docker_config(options, maelys_cli_option(context, "docker-config")) != MAELYS_OCI_OK ||
        maelys_oci_pull_options_set_timeout_ms(options, timeout_ms) != MAELYS_OCI_OK) {
        maelys_oci_pull_options_release(&options);
        return maelys_cli_fail(context, MAELYS_CLI_CODE_UNEXPECTED,
            "Report this defect to the command implementation.", "Cannot construct validated pull options.");
    }
    maelys_oci_pull_result_t *result = NULL;
    char *error = NULL;
    maelys_oci_result_t pulled = maelys_oci_pull(options, store,
        maelys_cli_operand(context, 0u), maelys_cli_option(context, "platform"), &result, &error);
    maelys_oci_pull_options_release(&options);
    int status;
    if (pulled != MAELYS_OCI_OK) {
        status = fail_with(context, pulled, error);
    } else {
        status = maelys_cli_succeed_trusted(context,
            maelys_oci_pull_result_receipt_json(result), NULL, MAELYS_CLI_EXIT_OK);
        maelys_oci_error_free(error);
    }
    maelys_oci_pull_result_release(&result);
    return status;
}

/* ---- list, verify, gc ----------------------------------------------------------------- */

static const maelys_cli_option_t store_options[] = {
    {MAELYS_CLI_ABSOLUTE_PATH("store", "DIRECTORY", STORE_SUMMARY)},
};

static int command_list(maelys_cli_context_t *context) {
    maelys_oci_document_t *document = NULL;
    char *error = NULL;
    maelys_oci_result_t result =
        maelys_oci_store_list(store_option(context), &document, &error);
    if (result != MAELYS_OCI_OK) return fail_with(context, result, error);
    size_t count = maelys_oci_document_count(document, "artifacts");
    for (size_t i = 0u; i < count; ++i) {
        char *record = maelys_oci_document_item_text(document, "artifacts", i);
        int emitted = record
            ? maelys_cli_emit_record_trusted(context, record, NULL) : -1;
        maelys_oci_text_free(record);
        if (emitted != 0) {
            maelys_oci_document_release(&document);
            return maelys_cli_fail(context, MAELYS_CLI_CODE_IO_FAILED, NULL,
                "Could not emit artifact record %zu.", i);
        }
    }
    maelys_oci_document_release(&document);
    return maelys_cli_finish_records(context, MAELYS_CLI_EXIT_OK);
}

static int command_verify(maelys_cli_context_t *context) {
    maelys_oci_document_t *document = NULL;
    char *error = NULL;
    int valid = 0;
    maelys_oci_result_t result = maelys_oci_store_verify(
        store_option(context), &document, &valid, &error);
    if (result != MAELYS_OCI_OK) return fail_with(context, result, error);
    return succeed_document(context, document,
        valid ? MAELYS_CLI_EXIT_OK : MAELYS_CLI_EXIT_VIOLATIONS);
}

static const maelys_cli_option_t gc_options[] = {
    {MAELYS_CLI_ABSOLUTE_PATH("store", "DIRECTORY", STORE_SUMMARY)},
    {MAELYS_CLI_UNSIGNED("grace-seconds", "SECONDS",
     "Age a stale lease or abandoned temporary state must reach before "
     "collection.", 0u, 0u), MAELYS_CLI_DEFAULT_OF(MAELYS_OCI_GC_DEFAULT_GRACE_SECONDS)},
    MAELYS_CLI_APPLY_OPTION,
};

static int command_gc(maelys_cli_context_t *context) {
    uint64_t grace_seconds = 0u; /* the catalog default arrives here */
    (void)maelys_cli_option_unsigned(context, "grace-seconds", &grace_seconds);
    maelys_oci_document_t *document = NULL;
    char *error = NULL;
    int valid = 0;
    maelys_oci_result_t result = maelys_oci_store_gc(store_option(context),
        maelys_cli_flag(context, "apply"), grace_seconds, &document, &valid,
        &error);
    if (result != MAELYS_OCI_OK) return fail_with(context, result, error);
    return succeed_document(context, document,
        valid ? MAELYS_CLI_EXIT_OK : MAELYS_CLI_EXIT_VIOLATIONS);
}

/* ---- remove ----------------------------------------------------------------------------- */

static const maelys_cli_operand_t remove_operands[] = {
    {MAELYS_CLI_OPERAND("REFERENCE",
     "Immutable reference ending with @sha256:HEX, or a bare sha256:HEX.")},
};

static const maelys_cli_option_t remove_options[] = {
    {MAELYS_CLI_STRING("platform", "OS/ARCH",
     "Platform of the artifact when the manifest has several.")},
    {MAELYS_CLI_ABSOLUTE_PATH("store", "DIRECTORY", STORE_SUMMARY)},
    MAELYS_CLI_APPLY_OPTION,
};

static int command_remove(maelys_cli_context_t *context) {
    int status = validate_platform_option(context);
    if (maelys_cli_replied(context)) return status;
    maelys_oci_document_t *document = NULL;
    char *error = NULL;
    maelys_oci_result_t result = maelys_oci_store_remove(store_option(context),
        maelys_cli_operand(context, 0u), maelys_cli_option(context, "platform"),
        maelys_cli_flag(context, "apply"), &document, &error);
    if (result != MAELYS_OCI_OK) return fail_with(context, result, error);
    return succeed_document(context, document, MAELYS_CLI_EXIT_OK);
}

/* ---- unpack-rootfs ---------------------------------------------------------------------- */

static const maelys_cli_operand_t unpack_operands[] = {
    {MAELYS_CLI_OPERAND_KIND("ARCHIVE",
     "Sealed rootfs.tar produced by import.", MAELYS_CLI_VALUE_ABSOLUTE_PATH)},
    {MAELYS_CLI_OPERAND_KIND("DESTINATION",
     "Empty directory with mode 0700 owned by the caller.",
     MAELYS_CLI_VALUE_ABSOLUTE_PATH)},
};

#if defined(__linux__)
static int command_unpack_rootfs(maelys_cli_context_t *context) {
    maelys_oci_document_t *document = NULL;
    char *error = NULL;
    maelys_oci_result_t result = maelys_oci_unpack_portable_root(
        maelys_cli_operand(context, 0u), maelys_cli_operand(context, 1u),
        &document, &error);
    if (result != MAELYS_OCI_OK) return fail_with(context, result, error);
    return succeed_document(context, document, MAELYS_CLI_EXIT_OK);
}
#define UNPACK_ROOTFS_COMMAND \
    MAELYS_CLI_EXECUTE("unpack-rootfs", "unpack-rootfs", \
     "Extract a sealed portable root archive.", command_unpack_rootfs)
#else
/* The portable archive keeps Linux byte-string names; a case-folding or
 * normalizing host filesystem would alias distinct entries. The command
 * stays described so agents see why it is absent. */
#define UNPACK_ROOTFS_COMMAND \
    MAELYS_CLI_EXECUTE("unpack-rootfs", "unpack-rootfs", \
     "Extract a sealed portable root archive.", NULL), \
    .unavailable = "portable OCI roots may only be unpacked on Linux"
#endif

/* ---- catalog ------------------------------------------------------------------------------ */

static const maelys_cli_command_t commands[] = {
    {MAELYS_CLI_READ("inspect", "inspect",
     "List the runnable manifests of an OCI layout directory or archive.",
     command_inspect),
     MAELYS_CLI_OPERANDS(source_operands), MAELYS_CLI_SCHEMA(oci_inspect_schema)},
    {MAELYS_CLI_TRANSACTION("import", "import",
     "Materialize one manifest of an OCI layout into the immutable store.",
     command_import),
     MAELYS_CLI_OPERANDS(source_operands), MAELYS_CLI_OPTIONS(import_options),
     MAELYS_CLI_SCHEMA(oci_import_schema)},
    {MAELYS_CLI_EXECUTE("pull", "pull",
     "Acquire an image from a registry over HTTPS and materialize it.",
     command_pull),
     MAELYS_CLI_OPERANDS(pull_operands), MAELYS_CLI_OPTIONS(pull_options),
     MAELYS_CLI_SCHEMA(oci_pull_schema)},
    {MAELYS_CLI_RECORDS("list", "list",
     "List the artifacts published in the store.", command_list),
     MAELYS_CLI_OPTIONS(store_options), MAELYS_CLI_SCHEMA(oci_list_schema)},
    {MAELYS_CLI_READ("verify", "verify",
     "Verify every blob, closure, artifact and lease of the store; exit 2 "
     "on integrity errors.", command_verify),
     MAELYS_CLI_OPTIONS(store_options), MAELYS_CLI_SCHEMA(oci_verify_schema)},
    {MAELYS_CLI_TRANSACTION("gc", "gc",
     "Collect unreachable blobs, stale leases and abandoned temporary state.",
     command_gc),
     MAELYS_CLI_OPTIONS(gc_options), MAELYS_CLI_SCHEMA(oci_gc_schema)},
    {MAELYS_CLI_TRANSACTION("remove", "remove",
     "Retire one artifact and its source closure unless a lease holds it.",
     command_remove),
     MAELYS_CLI_OPERANDS(remove_operands), MAELYS_CLI_OPTIONS(remove_options),
     MAELYS_CLI_SCHEMA(oci_remove_schema)},
    {UNPACK_ROOTFS_COMMAND,
     MAELYS_CLI_OPERANDS(unpack_operands),
     MAELYS_CLI_SCHEMA(oci_unpack_rootfs_schema)},
};

int main(int argc, char **argv) {
    maelys_cli_app_t app = {
        .program = "maelys-oci",
        .product = "Maelys OCI",
        .version = MAELYS_OCI_BUILD_VERSION,
        .summary = "bounded OCI acquisition and immutable artifact store",
        .commands = commands,
        .command_count = MAELYS_CLI_COUNT(commands),
        .agent_guidance =
            "STORE\n"
            "  The store defaults to $" MAELYS_OCI_ENV_STORE ", else "
            "$XDG_DATA_HOME/maelys-oci.\n"
            "  Import and pull materialize OCI layers independently of any runtime.",
    };
    return maelys_cli_main(&app, argc, argv);
}
